services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      VITE_PORT: 3000
      VITE_BASE_URL_BACKEND: http://localhost:5000 # URL do backend
      NODE_ENV: production

  frontend:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/app
      - /app/node_modules
    environment:
      TZ: America/Sao_Paulo
      DATABASE_URL: "mysql://USUARIO:SENHA@URL:PORTA/DBNAME?schema=public"
      PORT: 5000
      SECRET: SECRET_JWT_TOKEN
      NODE_ENV: production
